version: '3'
services:
  mysql:
    image: mysql:8.0.18
    container_name: mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=2048711712P!
    volumes:
      - ./mysql-log:/var/log/mysql
      - ./mysql-data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d
      - /etc/localtime:/etc/localtime:ro
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "12000:3306"
    restart: always
    networks:
      - default
      - mynetwork

  redis:
    image: redis:6
    container_name: redis-master
    restart: always
    volumes:
      - ./config/master/redis.conf:/usr/local/redis/redis.conf
      - ./.redis-data:/data
    ports:
      - "13301:6379"
    networks:
      - default
      - mynetwork

  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - "12300:5672"
      - "22300:15672"
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - ./data:/var/lib/rabbitmq
    networks:
      - default
      - mynetwork
  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: nacos1
    ports:
      - "12400:8848"
      - "13400:9848"
      - "13401:9849"
    volumes:
      - ./.nacos-data:/home/nacos/data
    networks:
      - default
      - mynetwork
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=hostname
      - TZ=Asiz/Shanghai
    restart: always
  minio:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z-cpuv1
    container_name: minio1
    restart: always
    volumes:
      - ./minio_data:/data
    ports:
      - "12500:9000"
      - "12501:9001"
    environment:
      - MINIO_ROOT_USER=rootroot
      - MINIO_ROOT_PASSWORD=rootroot123
    command: server /data --address ":9000" --console-address ":9001"
    networks:
      - default
      - mynetwork
networks:
  mynetwork:
    external: true
