version: '3'
services:
  gateway:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "15000:15000"
    networks:
      - default
      - mynetwork

  blog:
    build: ./blog-service/blog-server
    container_name: blog-service
    ports:
      - "15100:15100"
    networks:
      - default
      - mynetwork

  user:
    build: ./user-service/user-server
    container_name: user-service
    ports:
      - "15200:15200"
    networks:
      - default
      - mynetwork

  auth:
    build: ./auth-service/auth-server
    container_name: auth-service
    ports:
      - "15300:15300"
    networks:
      - default
      - mynetwork

  comment:
    build: ./comment-service/comment-server
    container_name: comment-service
    ports:
      - "15400:15400"
    networks:
      - default
      - mynetwork
  resource:
    build: ./resource-service/resource-mail
    container_name: resource-service
    ports:
      - "15500:15500"
    networks:
      - default
      - mynetwork


networks:
  mynetwork:
    external: true
